services:
  - type: web
    name: pronghorn-travels
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
