# Generated by Django 4.2 on 2025-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('from_county', models.CharField(max_length=100)),
                ('to_county', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Passenger', 'Passenger'), ('Parcel', 'Parcel')], max_length=10)),
                ('num_passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('parcel_weight', models.FloatField(blank=True, null=True)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa')], max_length=20)),
                ('mpesa_number', models.CharField(blank=True, max_length=15)),
                ('payment_code', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
