# Generated by Django 4.2 on 2025-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('14 Seater', '14 Seater'), ('Wish', 'Wish'), ('Noah', 'Noah'), ('Voxy', 'Voxy')], default='bus', max_length=20),
            preserve_default=False,
        ),
    ]
