# Generated by Django 4.2 on 2025-08-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_contactmessage_phone_alter_booking_departure_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fare',
            new_name='To_Pay_KES',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mpesa_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
    ]
